In [304]:
import numpy as numpy

In [305]:
# Írj egy olyan fügvényt, ami megfordítja egy 2d array oszlopait
# Be: [[1,2],[3,4]]
# Ki: [[2,1],[4,3]]
# column_swap()

def column_swap(matrix):
    return numpy.flip(matrix, axis=1)

print(column_swap([[1,2],[3,4]]))
print(column_swap([[]]))

[[2 1]
 [4 3]]
[]


In [306]:
#Készíts egy olyan függvényt ami összehasonlít két array-t és adjon vissza egy array-ben, hogy hol egyenlőek 
# Pl Be: [7,8,9], [9,8,7] 
# Ki: [1]
# compare_two_array()
# egyenlő elemszámúakra kell csak hogy működjön

def compare_two_array(array1, array2):
    if len(array1)!= len(array2):
        return []
    else:
        #megadja minden elementre hogy equal vagy sem true/false formájábam
        tmp = numpy.equal(array1, array2)
        #ahol true ahhoz rendel egy indexet pl.:
        #[false,true,false,true]
        #["kihagyja",1,"kihagyja",3]
        tmp = numpy.nonzero(tmp)[0]
        return tmp

print(compare_two_array(numpy.array([7,8,9]), numpy.array([9,8,7])))
print(compare_two_array([],[]))

[1]
[]


In [307]:
#Készíts egy olyan függvényt, ami vissza adja a megadott array dimenzióit:
# Be: [[1,2,3], [4,5,6]]
# Ki: "sor: 2, oszlop: 3, melyseg: 1"
# get_array_shape()
# 3D-vel még műküdnie kell!

def get_array_shape(arr):
    tmp = numpy.shape(arr)
    dim = numpy.ndim(arr)
    return f"sor: {tmp[0]}, oszlop: {tmp[1]}, melyseg: {dim}"

print(get_array_shape(numpy.array([[1,2,3], [4,5,6]])))

sor: 2, oszlop: 3, melyseg: 2


In [308]:
# Készíts egy olyan függvényt, aminek segítségével elő tudod állítani egy neurális hálózat tanításához szükséges Y-okat egy numpy array-ből. 
#Bementként add meg az array-t, illetve hogy mennyi class-od van. Kimenetként pedig adjon vissza egy 2d array-t, ahol a sorok az egyes elemek. Minden nullákkal teli legyen és csak ott álljon egyes, ahol a bementi tömb megjelöli
# Be: [1, 2, 0, 3], 4
# Ki: [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# encode_Y()

def encode_Y(input,classes):
    tmp = numpy.zeros((numpy.shape(input)[0],classes))
    for i in range(classes):
        numpy.put(tmp[i],input[i],1)

    return tmp

print(encode_Y([1, 2, 0,3],4))


[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [309]:
# A fenti feladatnak valósítsd meg a kiértékelését. Adj meg a 2d array-t és adj vissza a decodolt változatát
# Be:  [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# Ki:  [1, 2, 0, 3]
# decode_Y()

def decode_Y(input):
    return numpy.where(input == 1)[1]

print(decode_Y(numpy.array([[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]])))


[1 2 0 3]


In [310]:
# Készíts egy olyan függvényt, ami képes kiértékelni egy neurális háló eredményét! Bemenetként egy listát és egy array-t és adja vissza a legvalószínübb element a listából.
# Be: ['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]. 
# Ki: 'szilva'
# eval_classification()

def eval_classification(inputOne, inputTwo):
    return inputOne[numpy.argmax(inputTwo)]

print(eval_classification(['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]))

szilva


In [311]:
# Készíts egy olyan függvényt, ahol az 1D array-ben a páratlan számokat -1-re cseréli
# Be: [1,2,3,4,5,6]
# Ki: [-1,2,-1,4,-1,6]
# repalce_odd_numbers()

def replace_odd_numbers(input):
    tmp = numpy.where(input%2 == 1,-1, input)
    return tmp

print(replace_odd_numbers(numpy.array([1,2,3,4,5,6])))

[-1  2 -1  4 -1  6]


In [312]:
# Készíts egy olyan függvényt, ami egy array értékeit -1 és 1-re változtatja, attól függően, hogy az adott elem nagyobb vagy kisebb a paraméterként megadott számnál.
# Ha a szám kisebb mint a megadott érték, akkor -1, ha nagyobb vagy egyenlő, akkor pedig 1.
# Be: [1, 2, 5, 0], 2
# Ki: [-1, 1, 1, -1]
# replace_by_value()

def replace_by_value(arr, value):
    return numpy.where(arr < value , -1, 1)

print(replace_by_value(numpy.array([1, 2, 5, 0]), 2))

[-1  1  1 -1]


In [313]:
# Készítsd egy olyan függvényt, ami az array értékeit összeszorozza és az eredmény visszaadja
# Be: [1,2,3,4]
# Ki: 24
# array_multi()
# Ha több dimenziós a tömb, akkor az egész tömb elemeinek szorzatával térjen vissza

def array_multi(arr):
    return numpy.prod(arr)

print(array_multi(numpy.array([1,2,3,4])))

24


In [314]:
# Készítsd egy olyan függvényt, ami a 2D array értékeit összeszorozza és egy olyan array-el tér vissza, aminek az elemei a soroknak a szorzata
# Be: [[1, 2], [3, 4]]
# Ki: [2, 12]
# array_multi_2d()

def array_multi_2d(input):
    return numpy.prod(input, axis=1) #0=oszlop , 1=sor

print(array_multi_2d(numpy.array([[1, 2], [3, 4]])))

[ 2 12]


In [315]:
# Készíts egy olyan függvényt, amit egy meglévő numpy array-hez készít egy bordert nullásokkal. Bementként egy array-t várjon és kimenetként egy array jelenjen meg aminek van border-je
# Be: [[1,2],[3,4]]
# Ki: [[0,0,0,0],[0,1,2,0],[0,3,4,0],[0,0,0,0]]
# add_border()

def add_border(input):
    return numpy.pad(input, pad_width=1, mode='constant', constant_values=0)

print(add_border(numpy.array([[1,2],[3,4]])))


[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [316]:
# Készíts egy olyan függvényt ami két dátum között felsorolja az összes napot.
# Be: '2023-03', '2023-04'
# Ki: ['2023-03-01', '2023-03-02', .. , '2023-03-31',]
# list_days()

def list_days(date1, date2):
    return numpy.arange(date1, date2, dtype='datetime64[D]')

print(list_days(numpy.datetime64('2023-03'),numpy.datetime64('2023-04')))

['2023-03-01' '2023-03-02' '2023-03-03' '2023-03-04' '2023-03-05'
 '2023-03-06' '2023-03-07' '2023-03-08' '2023-03-09' '2023-03-10'
 '2023-03-11' '2023-03-12' '2023-03-13' '2023-03-14' '2023-03-15'
 '2023-03-16' '2023-03-17' '2023-03-18' '2023-03-19' '2023-03-20'
 '2023-03-21' '2023-03-22' '2023-03-23' '2023-03-24' '2023-03-25'
 '2023-03-26' '2023-03-27' '2023-03-28' '2023-03-29' '2023-03-30'
 '2023-03-31']


In [317]:
# Írj egy fügvényt ami vissza adja az aktuális dátumot az alábbi formában: YYYY-MM-DD
# Be:
# Ki: 2017-03-24 
def kismacska():
    return numpy.datetime64('now','D')

print(kismacska())

2023-03-07


In [318]:
# Írj egy olyan függvényt ami visszadja, hogy mennyi másodperc telt el 1970 január 01. 00:00:00 óta.
# Be: 
# Ki: másodpercben az idó, int-é kasztolva
# sec_from_1970()

def sec_from_1970():
    tmp = numpy.datetime64('now')-numpy.datetime64('1970-01-01 00:00:00')
    return tmp.astype('int64')

print(sec_from_1970())


1678228614
